services:  
  backend:
    build: .
    ports:
      - "3000:3000"  

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017' 
    volumes:
      - dbdata6:/data/db  

volumes:
  dbdata6:  