name: Deploy to Amazon ECS
on:
  push:
    branches:
      - main 
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ECR: ${{secrets.AWS_ECR_REPOSITORY}}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3 

      - name: Setup Terraform create ec2 instance
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"          
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform -chdir=terra-create-ec2/ init -input=false

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=terra-create-ec2/ plan -no-color -input=false

      - name: Terraform Apply
        id: apply
        run: terraform -chdir=terra-create-ec2/ apply -auto-approve -input=false
 