name: Deploy to Amazon ECS
on:
  push:
    branches:
      - main
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ECR: ${{secrets.AWS_ECR_REPOSITORY}}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy-ec2:
    name: "deploy EC2"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-name  sg_example_04 --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
      - name: instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "set accessable"
            echo "pull down respecitve branch for env" 
            sudo git config --global --add safe.directory '*'
            # sudo git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/ricnef2121/BACKEND-TODO-LIST.git --depth 1 --branch=main ~/BACKEND-TODO-LIST
            cd ~/BACKEND-TODO-LIST
            sudo git pull https://${{ secrets.GITHUB_TOKEN }}@github.com/ricnef2121/BACKEND-TODO-LIST.git main            
            echo "verify git pull"
            cd BACKEND-TODO-LIST
            git status
            sudo docker compose up            
      - name: Remove Github Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-name sg_example_04 --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
