name: Deploy to Amazon ECS
on:
  push:
    branches:
      - main 
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECS_CLUSTER: app_cluster
  CONTAINER_NAME: app
  ECS_SERVICE: app_service
  ECS_TD: .github/workflows/td.json

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform -chdir=terra-four-time/ init -input=false

      - name: Terraform Plan
        run: terraform -chdir=terra-four-time/ plan -input=false

      - name: Terraform Apply
        run: terraform -chdir=terra-four-time/ apply -auto-approve -input=false
      
      - name: Terraform output private_key
        run: terraform output -raw private_key
        