name: Deploy to Amazon ECS
on:
  push:
    branches:
      - main 
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECS_CLUSTER: app_cluster
  CONTAINER_NAME: app
  ECS_SERVICE: app_service
  ECS_TD: .github/workflows/td.json

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform -chdir=terra-create-ecr-repo/ init -input=false

      - name: Terraform Plan
        run: terraform -chdir=terra-create-ecr-repo/ plan -input=false

      - name: Terraform Apply
        run: terraform -chdir=terra-create-ecr-repo/ apply -auto-approve -input=false
      
      - name: Terraform output  
        run: |
          echo "::set-output name=instance_public_dns::$(terraform output elastic_ip)"
          output=$(terraform output elastic_ip) 
          echo $output
        working-directory: ./
        